name: medicine_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  change_app_package_name: ^1.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_spinkit: ^5.0.0
  flutter_svg: null
  http: null
  lint: ^1.7.2
  numberpicker: ^2.1.1
  path_provider: null
  photo_view: ^0.12.0
  provider: null
  pull_to_refresh: ^2.0.0
  shared_preferences: null
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/diller/
    - assets/images/
    - assets/icons/
    - assets/language/ru-RU.json
    - assets/language/en-US.json

  fonts:
    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins_SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins_Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
