name: medicine_app
description: A new Flutter project.
publish_to: "none"
version: 2.2.0+3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  awesome_notifications: ^0.7.4+1
  cached_network_image: null
  cupertino_icons: ^1.0.2
  firebase_core_platform_interface: ^4.5.1
  firebase_messaging: ^14.6.3
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_spinkit: ^5.0.0
  get: null
  get_storage:
  http: null
  path_provider: null
  photo_view: ^0.14.0
  provider: null
  pull_to_refresh: ^2.0.0
  restart_app: ^1.1.0
  share: ^2.0.4
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
